runtime: python27
api_version: 1
threadsafe: true
handlers:
  - url: /(.*\.(gif|png|jpg|css|js)(|\.map))$
    static_files: dist/andle/\1
    upload: dist/andle/(.*)(|\.map)

  - url: /(.*)
    static_files: dist/andle/index.html
    upload: dist/andle/index.html

skip_files:
  - e2e/
  - node_modules/
  - src/
  - coverage
  - ^(.*/)?\..*$
  - ^(.*/)?.*\.json$
  - ^(.*/)?.*\.md$
  - ^(.*/)?.*\.yaml$
  - ^LICENSE